# Generated by Django 2.1.7 on 2019-04-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCommunity_1622441019', '0002_admin_1622441019_issue_1622441019_provider_1622441019_prvidertype_1622441019_user_1622441019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider_1622441019',
            options={},
        ),
    ]
