# Generated by Django 2.1.7 on 2019-04-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCommunity_1622441019', '0003_auto_20190404_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider_1622441019',
        ),
    ]
