# Generated by Django 2.1.7 on 2019-04-04 01:50

import SmartCommunity_1622441019.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCommunity_1622441019', '0004_delete_provider_1622441019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider_1622441019',
            fields=[
                ('providerID', models.AutoField(db_column='providerID', primary_key=True, serialize=False)),
                ('providerName', models.CharField(blank=True, db_column='providerName', max_length=60, null=True)),
                ('phoneNumber', models.CharField(blank=True, db_column='phoneNumber', max_length=45, null=True)),
                ('emailAddress', models.CharField(blank=True, db_column='emailAddress', max_length=80, null=True)),
                ('providerPrice', models.CharField(blank=True, db_column='providerPrice', max_length=6, null=True)),
                ('providerType', SmartCommunity_1622441019.models.EnumField(choices=[('Please choose your Type', 'Please choose your type'), ('Water', 'Water'), ('Electronic', 'Electronic'), ('Car', 'Car'), ('Air', 'Air'), ('Fire', 'Fire'), ('House', 'House'), ('Clean', 'Clean')], default=0)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
    ]
